# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: false

# Outputting
permalink: pretty
baseurl: /
paginate: 5
title: Sillydev
tagline: 'Developing silly things'
url: http://sillydev.com
author:
  name: Murilo Fioravanti
  url: https://twitter.com/k0uta
  email: mail@sillydev.com
version: 0.0.1
OlderNewer
# 3rd parties
google_analytics: UA-60806528-1
disqus: k0uta